cb_list:
	defw	rlc_r		; $00
	defw	rlc_r		; $01
	defw	rlc_r		; $02
	defw	rlc_r		; $03
	defw	rlc_r		; $04
	defw	rlc_r		; $05
	defw	rlc_hlp		; $06
	defw	rlc_r		; $07
	defw	rrc_r		; $08
	defw	rrc_r		; $09
	defw	rrc_r		; $0A
	defw	rrc_r		; $0B
	defw	rrc_r		; $0C
	defw	rrc_r		; $0D
	defw	rrc_hlp		; $0E
	defw	rrc_r		; $0F
	defw	rl_r		; $10
	defw	rl_r		; $11
	defw	rl_r		; $12
	defw	rl_r		; $13
	defw	rl_r		; $14
	defw	rl_r		; $15
	defw	rl_hlp		; $16
	defw	rl_r		; $17
	defw	rr_r		; $18
	defw	rr_r		; $19
	defw	rr_r		; $1A
	defw	rr_r		; $1B
	defw	rr_r		; $1C
	defw	rr_r		; $1D
	defw	rr_hlp		; $1E
	defw	rr_r		; $1F
	defw	sla_r		; $20
	defw	sla_r		; $21
	defw	sla_r		; $22
	defw	sla_r		; $23
	defw	sla_r		; $24
	defw	sla_r		; $25
	defw	sla_hlp		; $26
	defw	sla_r		; $27
	defw	sra_r		; $28
	defw	sra_r		; $29
	defw	sra_r		; $2A
	defw	sra_r		; $2B
	defw	sra_r		; $2C
	defw	sra_r		; $2D
	defw	sra_hlp		; $2E
	defw	sra_r		; $2F
	defw	op_nop		; $30
	defw	op_nop		; $31
	defw	op_nop		; $32
	defw	op_nop		; $33
	defw	op_nop		; $34
	defw	op_nop		; $35
	defw	op_nop		; $36
	defw	op_nop		; $37
	defw	srl_r		; $38
	defw	srl_r		; $39
	defw	srl_r		; $3A
	defw	srl_r		; $3B
	defw	srl_r		; $3C
	defw	srl_r		; $3D
	defw	srl_hlp		; $3E
	defw	srl_r		; $3F
	defw	bit_b_r		; $40
	defw	bit_b_r		; $41
	defw	bit_b_r		; $42
	defw	bit_b_r		; $43
	defw	bit_b_r		; $44
	defw	bit_b_r		; $45
	defw	bit_b_hlp	; $46
	defw	bit_b_r		; $47
	defw	bit_b_r		; $48
	defw	bit_b_r		; $49
	defw	bit_b_r		; $4A
	defw	bit_b_r		; $4B
	defw	bit_b_r		; $4C
	defw	bit_b_r		; $4D
	defw	bit_b_hlp	; $4E
	defw	bit_b_r		; $4F
	defw	bit_b_r		; $50
	defw	bit_b_r		; $51
	defw	bit_b_r		; $52
	defw	bit_b_r		; $53
	defw	bit_b_r		; $54
	defw	bit_b_r		; $55
	defw	bit_b_hlp	; $56
	defw	bit_b_r		; $57
	defw	bit_b_r		; $58
	defw	bit_b_r		; $59
	defw	bit_b_r		; $5A
	defw	bit_b_r		; $5B
	defw	bit_b_r		; $5C
	defw	bit_b_r		; $5D
	defw	bit_b_hlp	; $5E
	defw	bit_b_r		; $5F
	defw	bit_b_r		; $60
	defw	bit_b_r		; $61
	defw	bit_b_r		; $62
	defw	bit_b_r		; $63
	defw	bit_b_r		; $64
	defw	bit_b_r		; $65
	defw	bit_b_hlp	; $66
	defw	bit_b_r		; $67
	defw	bit_b_r		; $68
	defw	bit_b_r		; $69
	defw	bit_b_r		; $6A
	defw	bit_b_r		; $6B
	defw	bit_b_r		; $6C
	defw	bit_b_r		; $6D
	defw	bit_b_hlp	; $6E
	defw	bit_b_r		; $6F
	defw	bit_b_r		; $70
	defw	bit_b_r		; $71
	defw	bit_b_r		; $72
	defw	bit_b_r		; $73
	defw	bit_b_r		; $74
	defw	bit_b_r		; $75
	defw	bit_b_hlp	; $76
	defw	bit_b_r		; $77
	defw	bit_b_r		; $78
	defw	bit_b_r		; $79
	defw	bit_b_r		; $7A
	defw	bit_b_r		; $7B
	defw	bit_b_r		; $7C
	defw	bit_b_r		; $7D
	defw	bit_b_hlp	; $7E
	defw	bit_b_r		; $7F
	defw	res_b_r		; $80
	defw	res_b_r		; $81
	defw	res_b_r		; $82
	defw	res_b_r		; $83
	defw	res_b_r		; $84
	defw	res_b_r		; $85
	defw	res_b_hlp	; $86
	defw	res_b_r		; $87
	defw	res_b_r		; $88
	defw	res_b_r		; $89
	defw	res_b_r		; $8A
	defw	res_b_r		; $8B
	defw	res_b_r		; $8C
	defw	res_b_r		; $8D
	defw	res_b_hlp	; $8E
	defw	res_b_r		; $8F
	defw	res_b_r		; $90
	defw	res_b_r		; $91
	defw	res_b_r		; $92
	defw	res_b_r		; $93
	defw	res_b_r		; $94
	defw	res_b_r		; $95
	defw	res_b_hlp	; $96
	defw	res_b_r		; $97
	defw	res_b_r		; $98
	defw	res_b_r		; $99
	defw	res_b_r		; $9A
	defw	res_b_r		; $9B
	defw	res_b_r		; $9C
	defw	res_b_r		; $9D
	defw	res_b_hlp	; $9E
	defw	res_b_r		; $9F
	defw	res_b_r		; $A0
	defw	res_b_r		; $A1
	defw	res_b_r		; $A2
	defw	res_b_r		; $A3
	defw	res_b_r		; $A4
	defw	res_b_r		; $A5
	defw	res_b_hlp	; $A6
	defw	res_b_r		; $A7
	defw	res_b_r		; $A8
	defw	res_b_r		; $A9
	defw	res_b_r		; $AA
	defw	res_b_r		; $AB
	defw	res_b_r		; $AC
	defw	res_b_r		; $AD
	defw	res_b_hlp	; $AE
	defw	res_b_r		; $AF
	defw	res_b_r		; $B0
	defw	res_b_r		; $B1
	defw	res_b_r		; $B2
	defw	res_b_r		; $B3
	defw	res_b_r		; $B4
	defw	res_b_r		; $B5
	defw	res_b_hlp	; $B6
	defw	res_b_r		; $B7
	defw	res_b_r		; $B8
	defw	res_b_r		; $B9
	defw	res_b_r		; $BA
	defw	res_b_r		; $BB
	defw	res_b_r		; $BC
	defw	res_b_r		; $BD
	defw	res_b_hlp	; $BE
	defw	res_b_r		; $BF
	defw	set_b_r		; $C0
	defw	set_b_r		; $C1
	defw	set_b_r		; $C2
	defw	set_b_r		; $C3
	defw	set_b_r		; $C4
	defw	set_b_r		; $C5
	defw	set_b_hlp	; $C6
	defw	set_b_r		; $C7
	defw	set_b_r		; $C8
	defw	set_b_r		; $C9
	defw	set_b_r		; $CA
	defw	set_b_r		; $CB
	defw	set_b_r		; $CC
	defw	set_b_r		; $CD
	defw	set_b_hlp	; $CE
	defw	set_b_r		; $CF
	defw	set_b_r		; $D0
	defw	set_b_r		; $D1
	defw	set_b_r		; $D2
	defw	set_b_r		; $D3
	defw	set_b_r		; $D4
	defw	set_b_r		; $D5
	defw	set_b_hlp	; $D6
	defw	set_b_r		; $D7
	defw	set_b_r		; $D8
	defw	set_b_r		; $D9
	defw	set_b_r		; $DA
	defw	set_b_r		; $DB
	defw	set_b_r		; $DC
	defw	set_b_r		; $DD
	defw	set_b_hlp	; $DE
	defw	set_b_r		; $DF
	defw	set_b_r		; $E0
	defw	set_b_r		; $E1
	defw	set_b_r		; $E2
	defw	set_b_r		; $E3
	defw	set_b_r		; $E4
	defw	set_b_r		; $E5
	defw	set_b_hlp	; $E6
	defw	set_b_r		; $E7
	defw	set_b_r		; $E8
	defw	set_b_r		; $E9
	defw	set_b_r		; $EA
	defw	set_b_r		; $EB
	defw	set_b_r		; $EC
	defw	set_b_r		; $ED
	defw	set_b_hlp	; $EE
	defw	set_b_r		; $EF
	defw	set_b_r		; $F0
	defw	set_b_r		; $F1
	defw	set_b_r		; $F2
	defw	set_b_r		; $F3
	defw	set_b_r		; $F4
	defw	set_b_r		; $F5
	defw	set_b_hlp	; $F6
	defw	set_b_r		; $F7
	defw	set_b_r		; $F8
	defw	set_b_r		; $F9
	defw	set_b_r		; $FA
	defw	set_b_r		; $FB
	defw	set_b_r		; $FC
	defw	set_b_r		; $FD
	defw	set_b_hlp	; $FE
	defw	set_b_r		; $FF
