ed_list:
	defw	op_nop2		; $00
	defw	op_nop2		; $01
	defw	op_nop2		; $02
	defw	op_nop2		; $03
	defw	op_nop2		; $04
	defw	op_nop2		; $05
	defw	op_nop2		; $06
	defw	op_nop2		; $07
	defw	op_nop2		; $08
	defw	op_nop2		; $09
	defw	op_nop2		; $0A
	defw	op_nop2		; $0B
	defw	op_nop2		; $0C
	defw	op_nop2		; $0D
	defw	op_nop2		; $0E
	defw	op_nop2		; $0F
	defw	op_nop2		; $10
	defw	op_nop2		; $11
	defw	op_nop2		; $12
	defw	op_nop2		; $13
	defw	op_nop2		; $14
	defw	op_nop2		; $15
	defw	op_nop2		; $16
	defw	op_nop2		; $17
	defw	op_nop2		; $18
	defw	op_nop2		; $19
	defw	op_nop2		; $1A
	defw	op_nop2		; $1B
	defw	op_nop2		; $1C
	defw	op_nop2		; $1D
	defw	op_nop2		; $1E
	defw	op_nop2		; $1F
	defw	op_nop2		; $20
	defw	op_nop2		; $21
	defw	op_nop2		; $22
	defw	op_nop2		; $23
	defw	op_nop2		; $24
	defw	op_nop2		; $25
	defw	op_nop2		; $26
	defw	op_nop2		; $27
	defw	op_nop2		; $28
	defw	op_nop2		; $29
	defw	op_nop2		; $2A
	defw	op_nop2		; $2B
	defw	op_nop2		; $2C
	defw	op_nop2		; $2D
	defw	op_nop2		; $2E
	defw	op_nop2		; $2F
	defw	op_nop2		; $30
	defw	op_nop2		; $31
	defw	op_nop2		; $32
	defw	op_nop2		; $33
	defw	op_nop2		; $34
	defw	op_nop2		; $35
	defw	op_nop2		; $36
	defw	op_nop2		; $37
	defw	op_nop2		; $38
	defw	op_nop2		; $39
	defw	op_nop2		; $3A
	defw	op_nop2		; $3B
	defw	op_nop2		; $3C
	defw	op_nop2		; $3D
	defw	op_nop2		; $3E
	defw	op_nop2		; $3F
	defw	in_r_cp		; $40
	defw	out_cp_r	; $41
	defw	sbc_hl_ss	; $42
	defw	ld_nnp_dd	; $43
	defw	op_neg		; $44
	defw	op_retn		; $45
	defw	op_im0		; $46
	defw	ld_i_a		; $47
	defw	in_r_cp		; $48
	defw	out_cp_r	; $49
	defw	adc_hl_ss	; $4A
	defw	ld_dd_nnp	; $4B
	defw	op_nop2		; $4C
	defw	op_reti		; $4D
	defw	op_nop2		; $4E
	defw	ld_r_a		; $4F
	defw	in_r_cp		; $50
	defw	out_cp_r	; $51
	defw	sbc_hl_ss	; $52
	defw	ld_nnp_dd	; $53
	defw	op_nop2		; $54
	defw	op_nop2		; $55
	defw	op_im1		; $56
	defw	ld_a_i		; $57
	defw	in_r_cp		; $58
	defw	out_cp_r	; $59
	defw	adc_hl_ss	; $5A
	defw	ld_dd_nnp	; $5B
	defw	op_nop2		; $5C
	defw	op_nop2		; $5D
	defw	op_im2		; $5E
	defw	ld_a_r		; $5F
	defw	in_r_cp		; $60
	defw	out_cp_r	; $61
	defw	sbc_hl_ss	; $62
	defw	ld_nnp_dd	; $63
	defw	op_nop2		; $64
	defw	op_nop2		; $65
	defw	op_nop2		; $66
	defw	op_rrd		; $67
	defw	in_r_cp		; $68
	defw	out_cp_r	; $69
	defw	adc_hl_ss	; $6A
	defw	ld_dd_nnp	; $6B
	defw	op_nop2		; $6C
	defw	op_nop2		; $6D
	defw	op_nop2		; $6E
	defw	op_rld		; $6F
	defw	in_r_cp		; $70
	defw	op_nop2		; $71
	defw	sbc_hl_ss	; $72
	defw	ld_nnp_dd	; $73
	defw	op_nop2		; $74
	defw	op_nop2		; $75
	defw	op_nop2		; $76
	defw	op_nop2		; $77
	defw	in_r_cp		; $78
	defw	out_cp_r	; $79
	defw	adc_hl_ss	; $7A
	defw	ld_dd_nnp	; $7B
	defw	op_nop2		; $7C
	defw	op_nop2		; $7D
	defw	op_nop2		; $7E
	defw	op_nop2		; $7F
	defw	op_nop2		; $80
	defw	op_nop2		; $81
	defw	op_nop2		; $82
	defw	op_nop2		; $83
	defw	op_nop2		; $84
	defw	op_nop2		; $85
	defw	op_nop2		; $86
	defw	op_nop2		; $87
	defw	op_nop2		; $88
	defw	op_nop2		; $89
	defw	op_nop2		; $8A
	defw	op_nop2		; $8B
	defw	op_nop2		; $8C
	defw	op_nop2		; $8D
	defw	op_nop2		; $8E
	defw	op_nop2		; $8F
	defw	op_nop2		; $90
	defw	op_nop2		; $91
	defw	op_nop2		; $92
	defw	op_nop2		; $93
	defw	op_nop2		; $94
	defw	op_nop2		; $95
	defw	op_nop2		; $96
	defw	op_nop2		; $97
	defw	op_nop2		; $98
	defw	op_nop2		; $99
	defw	op_nop2		; $9A
	defw	op_nop2		; $9B
	defw	op_nop2		; $9C
	defw	op_nop2		; $9D
	defw	op_nop2		; $9E
	defw	op_nop2		; $9F
	defw	op_ldi		; $A0
	defw	op_cpi		; $A1
	defw	op_ini		; $A2
	defw	op_outi		; $A3
	defw	op_nop2		; $A4
	defw	op_nop2		; $A5
	defw	op_nop2		; $A6
	defw	op_nop2		; $A7
	defw	op_ldd		; $A8
	defw	op_cpd		; $A9
	defw	op_ind		; $AA
	defw	op_outd		; $AB
	defw	op_nop2		; $AC
	defw	op_nop2		; $AD
	defw	op_nop2		; $AE
	defw	op_nop2		; $AF
	defw	op_ldir		; $B0
	defw	op_cpir		; $B1
	defw	op_inir		; $B2
	defw	op_otir		; $B3
	defw	op_nop2		; $B4
	defw	op_nop2		; $B5
	defw	op_nop2		; $B6
	defw	op_nop2		; $B7
	defw	op_lddr		; $B8
	defw	op_cpdr		; $B9
	defw	op_indr		; $BA
	defw	op_otdr		; $BB
	defw	op_nop2		; $BC
	defw	op_nop2		; $BD
	defw	op_nop2		; $BE
	defw	op_nop2		; $BF
	defw	op_nop2		; $C0
	defw	op_nop2		; $C1
	defw	op_nop2		; $C2
	defw	op_nop2		; $C3
	defw	op_nop2		; $C4
	defw	op_nop2		; $C5
	defw	op_nop2		; $C6
	defw	op_nop2		; $C7
	defw	op_nop2		; $C8
	defw	op_nop2		; $C9
	defw	op_nop2		; $CA
	defw	op_nop2		; $CB
	defw	op_nop2		; $CC
	defw	op_nop2		; $CD
	defw	op_nop2		; $CE
	defw	op_nop2		; $CF
	defw	op_nop2		; $D0
	defw	op_nop2		; $D1
	defw	op_nop2		; $D2
	defw	op_nop2		; $D3
	defw	op_nop2		; $D4
	defw	op_nop2		; $D5
	defw	op_nop2		; $D6
	defw	op_nop2		; $D7
	defw	op_nop2		; $D8
	defw	op_nop2		; $D9
	defw	op_nop2		; $DA
	defw	op_nop2		; $DB
	defw	op_nop2		; $DC
	defw	op_nop2		; $DD
	defw	op_nop2		; $DE
	defw	op_nop2		; $DF
	defw	op_nop2		; $E0
	defw	op_nop2		; $E1
	defw	op_nop2		; $E2
	defw	op_nop2		; $E3
	defw	op_nop2		; $E4
	defw	op_nop2		; $E5
	defw	op_nop2		; $E6
	defw	op_nop2		; $E7
	defw	op_nop2		; $E8
	defw	op_nop2		; $E9
	defw	op_nop2		; $EA
	defw	op_nop2		; $EB
	defw	op_nop2		; $EC
	defw	op_nop2		; $ED
	defw	op_nop2		; $EE
	defw	op_nop2		; $EF
	defw	op_nop2		; $F0
	defw	op_nop2		; $F1
	defw	op_nop2		; $F2
	defw	op_nop2		; $F3
	defw	op_nop2		; $F4
	defw	op_nop2		; $F5
	defw	op_nop2		; $F6
	defw	op_nop2		; $F7
	defw	op_nop2		; $F8
	defw	op_nop2		; $F9
	defw	op_nop2		; $FA
	defw	op_nop2		; $FB
	defw	op_nop2		; $FC
	defw	op_nop2		; $FD
	defw	op_nop2		; $FE
	defw	op_nop2		; $FF
