fd_list:
	defw	op_nop		; $00
	defw	op_nop		; $01
	defw	op_nop		; $02
	defw	op_nop		; $03
	defw	op_nop		; $04
	defw	op_nop		; $05
	defw	op_nop		; $06
	defw	op_nop		; $07
	defw	op_nop		; $08
	defw	op_nop		; $09
	defw	op_nop		; $0A
	defw	op_nop		; $0B
	defw	op_nop		; $0C
	defw	op_nop		; $0D
	defw	op_nop		; $0E
	defw	op_nop		; $0F
	defw	op_nop		; $10
	defw	op_nop		; $11
	defw	op_nop		; $12
	defw	op_nop		; $13
	defw	op_nop		; $14
	defw	op_nop		; $15
	defw	op_nop		; $16
	defw	op_nop		; $17
	defw	op_nop		; $18
	defw	op_nop		; $19
	defw	op_nop		; $1A
	defw	op_nop		; $1B
	defw	op_nop		; $1C
	defw	op_nop		; $1D
	defw	op_nop		; $1E
	defw	op_nop		; $1F
	defw	op_nop		; $20
	defw	ld_iy_nn	; $21
	defw	ld_nnp_iy	; $22
	defw	op_nop		; $23
	defw	op_nop		; $24
	defw	op_nop		; $25
	defw	op_nop		; $26
	defw	op_nop		; $27
	defw	op_nop		; $28
	defw	op_nop		; $29
	defw	ld_iy_nnp	; $2A
	defw	op_nop		; $2B
	defw	op_nop		; $2C
	defw	op_nop		; $2D
	defw	op_nop		; $2E
	defw	op_nop		; $2F
	defw	op_nop		; $30
	defw	op_nop		; $31
	defw	op_nop		; $32
	defw	op_nop		; $33
	defw	inc_iydp	; $34
	defw	dec_iydp	; $35
	defw	ld_iydp_n	; $36
	defw	op_nop		; $37
	defw	op_nop		; $38
	defw	op_nop		; $39
	defw	op_nop		; $3A
	defw	op_nop		; $3B
	defw	op_nop		; $3C
	defw	op_nop		; $3D
	defw	op_nop		; $3E
	defw	op_nop		; $3F
	defw	op_nop		; $40
	defw	op_nop		; $41
	defw	op_nop		; $42
	defw	op_nop		; $43
	defw	op_nop		; $44
	defw	op_nop		; $45
	defw	ld_r_iydp	; $46
	defw	op_nop		; $47
	defw	op_nop		; $48
	defw	op_nop		; $49
	defw	op_nop		; $4A
	defw	op_nop		; $4B
	defw	op_nop		; $4C
	defw	op_nop		; $4D
	defw	ld_r_iydp	; $4E
	defw	op_nop		; $4F
	defw	op_nop		; $50
	defw	op_nop		; $51
	defw	op_nop		; $52
	defw	op_nop		; $53
	defw	op_nop		; $54
	defw	op_nop		; $55
	defw	ld_r_iydp	; $56
	defw	op_nop		; $57
	defw	op_nop		; $58
	defw	op_nop		; $59
	defw	op_nop		; $5A
	defw	op_nop		; $5B
	defw	op_nop		; $5C
	defw	op_nop		; $5D
	defw	ld_r_iydp	; $5E
	defw	op_nop		; $5F
	defw	op_nop		; $60
	defw	op_nop		; $61
	defw	op_nop		; $62
	defw	op_nop		; $63
	defw	op_nop		; $64
	defw	op_nop		; $65
	defw	ld_r_iydp	; $66
	defw	op_nop		; $67
	defw	op_nop		; $68
	defw	op_nop		; $69
	defw	op_nop		; $6A
	defw	op_nop		; $6B
	defw	op_nop		; $6C
	defw	op_nop		; $6D
	defw	ld_r_iydp	; $6E
	defw	op_nop		; $6F
	defw	ld_iydp_r	; $70
	defw	ld_iydp_r	; $71
	defw	ld_iydp_r	; $72
	defw	ld_iydp_r	; $73
	defw	ld_iydp_r	; $74
	defw	ld_iydp_r	; $75
	defw	op_nop		; $76
	defw	ld_iydp_r	; $77
	defw	op_nop		; $78
	defw	op_nop		; $79
	defw	op_nop		; $7A
	defw	op_nop		; $7B
	defw	op_nop		; $7C
	defw	op_nop		; $7D
	defw	ld_r_iydp	; $7E
	defw	op_nop		; $7F
	defw	op_nop		; $80
	defw	op_nop		; $81
	defw	op_nop		; $82
	defw	op_nop		; $83
	defw	op_nop		; $84
	defw	op_nop		; $85
	defw	add_a_iydp	; $86
	defw	op_nop		; $87
	defw	op_nop		; $88
	defw	op_nop		; $89
	defw	op_nop		; $8A
	defw	op_nop		; $8B
	defw	op_nop		; $8C
	defw	op_nop		; $8D
	defw	adc_a_iydp	; $8E
	defw	op_nop		; $8F
	defw	op_nop		; $90
	defw	op_nop		; $91
	defw	op_nop		; $92
	defw	op_nop		; $93
	defw	op_nop		; $94
	defw	op_nop		; $95
	defw	sub_iydp	; $96
	defw	op_nop		; $97
	defw	op_nop		; $98
	defw	op_nop		; $99
	defw	op_nop		; $9A
	defw	op_nop		; $9B
	defw	op_nop		; $9C
	defw	op_nop		; $9D
	defw	sbc_a_iydp	; $9E
	defw	op_nop		; $9F
	defw	op_nop		; $A0
	defw	op_nop		; $A1
	defw	op_nop		; $A2
	defw	op_nop		; $A3
	defw	op_nop		; $A4
	defw	op_nop		; $A5
	defw	and_iydp	; $A6
	defw	op_nop		; $A7
	defw	op_nop		; $A8
	defw	op_nop		; $A9
	defw	op_nop		; $AA
	defw	op_nop		; $AB
	defw	op_nop		; $AC
	defw	op_nop		; $AD
	defw	xor_iydp	; $AE
	defw	op_nop		; $AF
	defw	op_nop		; $B0
	defw	op_nop		; $B1
	defw	op_nop		; $B2
	defw	op_nop		; $B3
	defw	op_nop		; $B4
	defw	op_nop		; $B5
	defw	or_iydp		; $B6
	defw	op_nop		; $B7
	defw	op_nop		; $B8
	defw	op_nop		; $B9
	defw	op_nop		; $BA
	defw	op_nop		; $BB
	defw	op_nop		; $BC
	defw	op_nop		; $BD
	defw	cp_iydp		; $BE
	defw	op_nop		; $BF
	defw	op_nop		; $C0
	defw	op_nop		; $C1
	defw	op_nop		; $C2
	defw	op_nop		; $C3
	defw	op_nop		; $C4
	defw	op_nop		; $C5
	defw	op_nop		; $C6
	defw	op_nop		; $C7
	defw	op_nop		; $C8
	defw	op_nop		; $C9
	defw	op_nop		; $CA
	defw	op_nop		; $CB
	defw	op_nop		; $CC
	defw	op_nop		; $CD
	defw	op_nop		; $CE
	defw	op_nop		; $CF
	defw	op_nop		; $D0
	defw	op_nop		; $D1
	defw	op_nop		; $D2
	defw	op_nop		; $D3
	defw	op_nop		; $D4
	defw	op_nop		; $D5
	defw	op_nop		; $D6
	defw	op_nop		; $D7
	defw	op_nop		; $D8
	defw	op_nop		; $D9
	defw	op_nop		; $DA
	defw	op_nop		; $DB
	defw	op_nop		; $DC
	defw	op_nop		; $DD
	defw	op_nop		; $DE
	defw	op_nop		; $DF
	defw	op_nop		; $E0
	defw	pop_iy		; $E1
	defw	op_nop		; $E2
	defw	ex_spp_iy	; $E3
	defw	op_nop		; $E4
	defw	push_iy		; $E5
	defw	op_nop		; $E6
	defw	op_nop		; $E7
	defw	op_nop		; $E8
	defw	op_nop		; $E9
	defw	op_nop		; $EA
	defw	op_nop		; $EB
	defw	op_nop		; $EC
	defw	op_nop		; $ED
	defw	op_nop		; $EE
	defw	op_nop		; $EF
	defw	op_nop		; $F0
	defw	op_nop		; $F1
	defw	op_nop		; $F2
	defw	op_nop		; $F3
	defw	op_nop		; $F4
	defw	op_nop		; $F5
	defw	op_nop		; $F6
	defw	op_nop		; $F7
	defw	op_nop		; $F8
	defw	ld_sp_iy	; $F9
	defw	op_nop		; $FA
	defw	op_nop		; $FB
	defw	op_nop		; $FC
	defw	op_nop		; $FD
	defw	op_nop		; $FE
	defw	op_nop		; $FF
